### ISSUE TITLE
give setting to ignore game version checks

### ISSUE THREAD

**Issue by ezio416** [XertroV/tm-ghosts-plus-plus#11]
Being able to bypass the game version check is nice, but as it currently is, reloading the plugin forgets my choice. I'd like this to be a persistent setting so when the game updates, I can just take the risk without having to click the button every time until the plugin is updated.

**Comment by iAroc** [comment]
How do you even bypass the check so that you can use it?

**Comment by ezio416** [comment]
It's in the last settings tab

**Comment by iAroc** [comment]
https://i.imgur.com/m8aOASq.png guess i will just wait until the plugin gets updated

**Comment by XertroV** [comment]
Yeah it's broken atm

@ezio416 I can understand the desire for this, but the reason it isn't like this atm is because it could leave you in a crash-reset loop. I mean it shouldn't b/c it doesn't do anything outside a map so you could disable it, but it's complexity where it probably doesn't need to be. 

An alternate idea that comes to me is that you import a function you can call to bypass it. then you can write a little plugin that calls that and nothing else. (the import stuff works even if the function isn't exported explicitly)

**Comment by ezio416** [comment]
I like the alternate idea and it seems to work. I've made a PR #12 to help myself with getting/setting `GameVersionSafe`

**Comment by XertroV** [comment]
Closing as resolved via importing the relevant functions
