### ISSUE TITLE
can't hide personal best ghost

### ISSUE THREAD

**Issue by ezio416** [XertroV/tm-ghosts-plus-plus#6]
I'm not able to use any plugins like Dashboard, Current Effects, or Current Surfaces that rely on one ghost being on-screen to see more info from the ghost I'm watching. It seems I can get it to work if I select another ghost, toggle my own ghost (by username from the leaderboard) a few times, then finally I can disable my PB ghost, then hide my leaderboard ghost. Very annoying workaround, and I can't find a consistent way to do that, it just seems random whether it'll work or not with enough clicks.

If my leaderboard ghost and my PB are both shown, it shows 2 ghosts in the same location, doubling the engine sounds which is quite unpleasant.
<img width="448" alt="Screenshot 2023-10-20 185642" src="https://github.com/XertroV/tm-ghosts-plus-plus/assets/37951898/192191ac-9c6d-4e5d-9375-05a4f7047780">

**Comment by ezio416** [comment]
The input display is nice and all, but nowhere near as much information as full Dashboard or my other plugins mentioned above.

**Comment by Valteur** [comment]
I had the same issue. With 0.3.3, I have different issues:

* Sometimes I get https://github.com/XertroV/tm-ghosts-plus-plus/issues/1 when clicking on my own ghost
* Here only Mudda's ghost is loaded, not my ghost, despite the eye thingy being on: 
![2023-10-21 14_40_35058945](https://github.com/XertroV/tm-ghosts-plus-plus/assets/87531948/3c035c9b-bfc7-44bd-b6f4-9a09517b5ede)
* When watching my own leaderboard ghost, and then hiding PB ghost, I have to manually spectate my ghost in Ghosts++ widget to go back to spectating my ghost.

**Comment by XertroV** [comment]
This is probably due to me not handling the PB ghost case properly. Will look into this so it works like you'd expect.

**Comment by XertroV** [comment]
> The input display is nice and all, but nowhere near as much information as full Dashboard or my other plugins mentioned above.

@ezio416 Yeah -- it's some minimal code copied from dashboard. Instead of copying more or reimplementing, I've made a PR to dashboard so I can inform it of the vehicle to show data for. That way you keep your styles and things as well. Provided that patch is merged and dashboard updated, I'll remove the current stuff in favor of proper dashboard integration

**Comment by Valteur** [comment]
https://github.com/XertroV/tm-ghosts-plus-plus/blob/master/src/MLEventHook.as#L158-L170 can these lines make you select the PB ghost instead of the player's ghost as the ghost to spectate ? They both have the same GhostLogin.

Looking at the log where I make the bug appear (watch my own ghost, then hide pb ghost, then in ghosts++ widget spectate my own ghost):
 ![2023-10-28 01_19_50059195](https://github.com/XertroV/tm-ghosts-plus-plus/assets/87531948/d91829bd-cc01-4e6c-b353-fabb83a413be)
It looks like I watched ghost 0 when I clicked on me in the leaderboard, then I watched ghost 2 when I clicked on the real "NewerCompte" ghost in the ghosts++ widget.

**Comment by Valteur** [comment]
Adding 

`            if (mgr2.Ghosts[i].GhostModel.GhostNickname.EndsWith("Personal best")) continue;`

At the beginning of these two loops: https://github.com/XertroV/tm-ghosts-plus-plus/blob/9b03369f839c50d52708e7e5fc68134be1519540/src/MLEventHook.as#L158-L170 fixed the issue for me.

**Comment by XertroV** [comment]
Cool thanks.

**Comment by XertroV** [comment]
Also I fixed the thing showing your ghost as on when it's not
