### ISSUE TITLE
PB Ghost sometimes starts earlier than it should when racing.

### ISSUE THREAD

**Issue by Valteur** [XertroV/tm-ghosts-plus-plus#7]
https://clips.twitch.tv/SolidTalentedHamburgerBudStar-C72IAPyLVK86iInx for an instance of it happening. Basically, the ghost starts immediately instead of waiting for the end of the countdown.

I have seen Scrappie and me have it too.

Unchecking Keep Existing in the advanced settings or resetting the map are workarounds.

Update: might be related to https://github.com/XertroV/tm-ghosts-plus-plus/issues/6 because you can see the eye next to "LarsTM" in the leaderboard flickering when the ghost starts early.

**Comment by Valteur** [comment]
Another issue: https://clips.twitch.tv/PhilanthropicFunnyFalconTriHard-8lAP7cpSG4JCfiP_

Not sure if it's related.

**Comment by XertroV** [comment]
The PB is gone because the scrubber is at 5 minutes (probably playground time or something). 
![image](https://github.com/XertroV/tm-ghosts-plus-plus/assets/1046448/d843b2c0-3aeb-448a-a60d-372a13c22408)
In this case if Lars used the scrubber it should have come back. The reason it disappeared when he hit 2x is that set ghosts current time is called every frame in that case (any speed other than 1x). When ghosts are at 1x it is not called every frame.

I did confirm that there's a bug where if you have ghosts on 2.0x and restart the run then it will not reset the scrubber.

**Comment by Valteur** [comment]
I don't think it's fixed. With master I need to watch a ghost to fix the ghost being away, a reset is not enough. It feels as if `bool _SpawnPlayer(CMwStack &in stack)` is only called when going back from spectating, it is not called during a reset.

**Comment by Valteur** [comment]
I tried adding `Call_Ghosts_SetStartTime(ps, -1);` to `ResetAll`. It fixes the problem most times, except sometimes when the scrubber is on screen, it gets instantly overwritten by `SetProgress` through this line: https://github.com/XertroV/tm-ghosts-plus-plus/blob/master/src/Scrubber.as#L283 because `(t > 0. && Math::Abs(t - setProg) / t * 1000. >= 1.0)` is true.

Calling `SetProgress(0)` before `Call_Ghosts_SetStartTime(ps, -1);` in `ResetAll` seems to work, but I am sure you can find the best solution.

**Comment by XertroV** [comment]
I just stopped blocking calls to SetStartTime(-1). It's not necessary atm (might have been in the past), so if that's what fixes it the current build should work.
